name: resume_builder_app
description: AI-powered Resume Builder with analysis
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1

  # File picker & PDF
  file_picker: ^10.3.3
  path_provider: ^2.1.2
  syncfusion_flutter_pdfviewer: ^31.1.20

  # UI & utilities
  provider: ^6.1.2
  intl: ^0.20.2

  # HTTP & networking
  http: ^1.2.2
  dio: ^5.2.1
  image_picker: ^1.1.2
  flutter_dotenv: ^6.0.0

  # PDF generation and printing
  pdf: ^3.11.0
  printing: ^5.12.0

  # Fonts & Icons
  google_fonts: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/templates/
    - .env
    - assets/icons/

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"  # Use a square image (e.g. 512x512)
  min_sdk_android: 21
